sample_app/config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'user/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'sigup'   => 'users#new'
end

sample_app/app/models/user.rb
class User < ActiveRecord::Base
  # callback
  before_save { self.email = email.downcase }
  # name
  validates :name,  presence: true, length: { maximum: 50 }
  # email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }


end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

sample_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about

  end
  def contact

  end
  def sigup

  end

end

sample_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

sample_app/app/helpers/application_helper.rb
module ApplicationHelper
end

sample_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

sample_app/app/helpers/users_helper.rb
module UsersHelper
end

sample_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

sample_app/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body >
  <%= render 'layouts/header'%>

  <div class="container" id="content">
    <%= yield %>

    <%= render 'layouts/footer'%>
  </div>



</body>
</html>

sample_app/app/views/static_pages/about.html.erb
<h1>about la day</h1>
<p>muon biet gi thi bam vao <a href="http://www.youtube.com">day</a></p>

sample_app/app/views/static_pages/contact.html.erb
<div id = "contact">
 <h1>Contact me</h1>
<div><a href="http://facebook.com">press here</a></div>
</div>

sample_app/app/views/static_pages/help.html.erb
<h1>Helper</h1>
<p><a href="http://bongdaplus.vn">tai day</a></p>

sample_app/app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>view hompage</h1>
  <p><a href="http://www.vnexpress.net">tai day</a></p>
  <%= link_to "Sign up now!", sigup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("ruby.jpg", alt: 'ruby'), 'http://www.rubyonrails.org' %>

sample_app/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>